# This file was generated by GoReleaser. DO NOT EDIT.
cask "pbmate" do
  name "pbmate"
  desc "TUI companion for Percona Backup for MongoDB"
  homepage "https://github.com/jcechace/pbmate"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pbmate"

  on_macos do
    on_arm do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_darwin_arm64.tar.gz"
      sha256 "ecbfe79c497833d1207dd98bd9878aeba02f9c5292eb5ea38605cb7331a49abe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_linux_amd64.tar.gz"
      sha256 "3b4eb22313da369a00c551d10685b629eaf830dba5217b50b29b67df14847ba7"
    end
    on_arm do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_linux_arm64.tar.gz"
      sha256 "3d0d44082ea7434b569ed430c96a55b14821c3d8d607b276cbdf49c052a0ea96"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pbmate"]
    end
  end

  # No zap stanza required
end
