# This file was generated by GoReleaser. DO NOT EDIT.
cask "pbmate" do
  name "pbmate"
  desc "TUI companion for Percona Backup for MongoDB"
  homepage "https://github.com/jcechace/pbmate"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pbmate"

  on_macos do
    on_arm do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_darwin_arm64.tar.gz"
      sha256 "17cf38507d9aff90b0d14d22daea26053202a7bd13cb38162acd5e18a4c6b1da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_linux_amd64.tar.gz"
      sha256 "9ea974586b49aa9fafe9d6c98905c606a7bef2f67da1506079ab4ee2f821ae01"
    end
    on_arm do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_linux_arm64.tar.gz"
      sha256 "f530a622173eeacb46ae2d3a0d35b4a41cb6a40898e8c29bfc9e131233dcb42c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pbmate"]
    end
  end

  # No zap stanza required
end
