# This file was generated by GoReleaser. DO NOT EDIT.
cask "pbmate" do
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_darwin_arm64.tar.gz"
      sha256 "6ff80df7b45e2429a83d532d4f09bb505fd0d9542d4a137d1af9719bdd320535"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_linux_amd64.tar.gz"
      sha256 "929695f8947790604bc2237524f44aa76c6c17d7184971b457042036555159d5"
    end
    on_arm do
      url "https://github.com/jcechace/pbmate/releases/download/v#{version}/pbmate_#{version}_linux_arm64.tar.gz"
      sha256 "51f855763c182abfb4f5df91965cf2f91f7065ab90b5d0dfe7894469172a8fbf"
    end
  end

  name "pbmate"
  desc "TUI companion for Percona Backup for MongoDB"
  homepage "https://github.com/jcechace/pbmate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pbmate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pbmate"]
    end
  end

  # No zap stanza required

end
